### ISSUE TITLE
Make `metadata` required property in `PortableDid`

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/web5-swift#53]
Details here: https://github.com/TBD54566975/web5-spec/pull/152

**Comment by AlexHsieh** [comment]
this issue is addressed in PR #50  commit [e099b77](https://github.com/TBD54566975/web5-swift/pull/50/commits/e099b7733f67a5c0643b4e1c41b6406fce4f1097#diff-7ec36d00c7398ab016e20059ca6d68b91468a038f8ecb5b66507d2ce477a747f)
